#! /usr/bin/env python2.7

from latte.proto.read import PTX
from latte.make import model
import sys

if len(sys.argv) != 3:
    print "Improperly formated command"
    exit()

f = PTX(sys.argv[1])
layers = f.compose()

ml = model()

for l in layers:
    ml.add_layer(l[0], l[1], l[2], l[3], l[4])

ml.run(sys.argv[2])
